# Site settings
title: Asynchronous concepts
email: jonathan.r.beaumont@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Concepts are a method of desinging asynchronous circuits from behaviours
  , at signal-, gate- or protocol level. All concepts can be composed,
  providing an intuitive method of specifying circuits. This blog explains concepts,
  from the basics to more complicated examples.
baseurl: "/concepts-blog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jrbeaumont

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
